version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'

  parent:
    build: .
    command: ts-node-dev src/server.ts
    environment:
      - ROLE=parent
      - FILE_COUNT=10
      - FILE_SIZE=1
      - S3_BUCKET=mast-dev-intw-test01
    depends_on:
      - rabbitmq

  worker1:
    build: .
    command: ts-node-dev src/server.ts
    environment:
      - ROLE=worker
    depends_on:
      - rabbitmq

  worker2:
    build: .
    command: ts-node-dev src/server.ts
    environment:
      - ROLE=worker
    depends_on:
      - rabbitmq

  worker3:
    build: .
    command: ts-node-dev src/server.ts
    environment:
      - ROLE=worker
    depends_on:
      - rabbitmq

  worker4:
    build: .
    command: ts-node-dev src/server.ts
    environment:
      - ROLE=worker
    depends_on:
      - rabbitmq
